### ISSUE TITLE
Jade has been renamed to Pug

### ISSUE THREAD

**Issue by dashtink** [nanobox-quickstarts/nanobox-expressjs#1]
Jade has been forced to rename to Pug due to trademark issues. 

> This project was formerly known as "Jade." However, it has been revealed to us that "Jade" is a registered trademark, and as a result a rename is needed. 

https://github.com/pugjs/pug

**Comment by jimulle** [comment]
I submitted a [pull request](https://github.com/nanobox-quickstarts/nanobox-express/pull/3) last night swapping Jade for Pug.

**Comment by sanderson** [comment]
Resolved by #1a3e4b4ec384cd95a13def00f4c487dfa232af7d
